version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: task-scheduler-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  scheduler-node-1:
    build: .
    container_name: task-scheduler-node-1
    ports:
      - "8080:8080"
      - "9090:9090"
      - "8081:8081"
    environment:
      - NODE_ID=node-1
      - HTTP_ADDRESS=:8080
      - GRPC_ADDRESS=:9090
      - RAFT_ADDRESS=:8081
      - REDIS_ADDRESS=redis:6379
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    command: ["./scheduler", "-node-id=node-1", "-http-addr=:8080", "-grpc-addr=:9090", "-redis-addr=redis:6379"]

  scheduler-node-2:
    build: .
    container_name: task-scheduler-node-2
    ports:
      - "8082:8080"
      - "9091:9090"
      - "8083:8081"
    environment:
      - NODE_ID=node-2
      - HTTP_ADDRESS=:8080
      - GRPC_ADDRESS=:9090
      - RAFT_ADDRESS=:8081
      - REDIS_ADDRESS=redis:6379
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    command: ["./scheduler", "-node-id=node-2", "-http-addr=:8080", "-grpc-addr=:9090", "-redis-addr=redis:6379", "-peers=scheduler-node-1:8081"]

  scheduler-node-3:
    build: .
    container_name: task-scheduler-node-3
    ports:
      - "8084:8080"
      - "9092:9090"
      - "8085:8081"
    environment:
      - NODE_ID=node-3
      - HTTP_ADDRESS=:8080
      - GRPC_ADDRESS=:9090
      - RAFT_ADDRESS=:8081
      - REDIS_ADDRESS=redis:6379
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    command: ["./scheduler", "-node-id=node-3", "-http-addr=:8080", "-grpc-addr=:9090", "-redis-addr=redis:6379", "-peers=scheduler-node-1:8081,scheduler-node-2:8081"]

  scheduler-node-4:
    build: .
    container_name: task-scheduler-node-4
    ports:
      - "8086:8080"
      - "9093:9090"
      - "8087:8081"
    environment:
      - NODE_ID=node-4
      - HTTP_ADDRESS=:8080
      - GRPC_ADDRESS=:9090
      - RAFT_ADDRESS=:8081
      - REDIS_ADDRESS=redis:6379
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    command: ["./scheduler", "-node-id=node-4", "-http-addr=:8080", "-grpc-addr=:9090", "-redis-addr=redis:6379", "-peers=scheduler-node-1:8081,scheduler-node-2:8081,scheduler-node-3:8081"]

volumes:
  redis_data: 